name: Continous CI

permissions:
  contents: write

on:
  push:
    branches: [ "test-ci" ]
  pull_request:
    branches: [ "test-ci" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up variables
      id: date
      run: |
       cd src
       echo "VVERSION=$(cat VERSION)" >> $GITHUB_ENV
       echo "GH_RELEASE_FILE=sglauncher-$(cat ./VERSION)-$(ldd --version | awk '/ldd/{print "-gnu-" $NF}')" >> $GITHUB_ENV

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          libgtk-3-dev \
          pkg-config \

    - name: Build with GCC
      run: |
        cd src
        make sglauncher CC=gcc
        strip sglauncher
        mv sglauncher ../${{ env.GH_RELEASE_FILE }}

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        name: Release ${{ env.VVERSION }}
        body: ${{ github.event.head_commit.message }}
        tag_name: ${{ env.VVERSION }}
        files: |
            ${{ env.GH_RELEASE_FILE }}